name: 🦆 Update On New Migrations

on:
  push:
    paths:
    - '**/migrations/**.js'
    - '**/migrations/**.ts'
    branches:
      - main

jobs:
  notify_on_migrations:
    name: 🦆 Notify On New Migrations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get all changed files
        id: changed-files
        run: |
          allchanged="$(git log --name-only --pretty="format:" ${{ github.event.before }}..${{ github.event.after }} | sort -u)"
          onlymigrations="$(echo "$allchanged" | grep /migrations/)"
          echo "::set-output name=all-changed::$allchanged"
          echo "::set-output name=all-migrations::$onlymigrations"
      # - name: test step Outputs
      #   run:
      #     echo ${{ steps.changed-files.outputs.all-migrations }}
      - name: 💬 Send Slack Message
        # if: steps.verify-changed-files.outputs.files_changed == 'true'
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "title": " New Migrations Added",
              "message": "${{ steps.changed-files.outputs.all-migrations }}"
            }
        # Outputs: "New Migrations Added:\n===\n - new.txt\n - test_directory/new.txt"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TEST }}