name: 🦆 Update On New Migrations

on:
  push:
    paths:
    - '**/migrations/**.js'
    - '**/migrations/**.ts'
    branches:
      - main

jobs:
  notify_on_migrations:
    name: 🦆 Notify On New Migrations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get all changed files
        id: changed-files
        run: |
          allchanged="$(git log --name-only --pretty="format:" ${{ github.event.before }}..${{ github.event.after }} | sort -u)"
          echo all changed files:
          echo $allchanged
          echo
          onlymigrations="$(echo $allchanged | sed -E 's/ /\n/g' | grep \/migrations\/)"
          echo only migrations:
          echo $onlymigrations
          echo
          formattedmessage="$(echo $onlymigrations | sed -E 's/ /\n/g' | sed -E 's/^(.*)\/migrations\/(.*)/\- \2/g' sed '$!s/$/\\n/' file | tr -d '\n')"
          echo formatted message:
          echo $formattedmessage
          echo 
          echo "::set-output name=all-changed::$allchanged"
          echo "::set-output name=all-migrations::$onlymigrations"
          echo "::set-output name=formatted-message::$formattedmessage"
    # ${formattedmessage//$'\n'/'%0A'}"
      - name: 💬 Send Slack Message
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "title": " New Migrations Added",
              "message": "${{ steps.changed-files.outputs.formatted-message }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TEST }}